---
name: Connect-Smart WG Client
version: 1.2.2
slug: cs_wg_client
description: Fast, modern, secure Wireguard tunnel (client)
url: https://github.com/Connect-Smart/remote-wireguard/
arch:
  - aarch64
  - amd64
  - armv7
apparmor: true
host_network: true
init: false
privileged:
  - NET_ADMIN
  - SYS_MODULE
devices:
  - /dev/net/tun
map:
  - type: config   # toegang tot /data/options.json
    read_only: false
options:
  portal_url: ""
  enrollment_token: ""
  verify_ssl: true
  monitor_enabled: true
  monitor_target: 10.8.0.1
  monitor_interval: 30
schema:
  portal_url: str?
  enrollment_token: str?
  verify_ssl: bool?
  monitor_enabled: bool?
  monitor_target: str?
  monitor_interval: int?
