---
name: Connect-Smart WG Client
version: 1.3.9
slug: cs_wg_client
description: Connect-Smart WireGuard client for Remote Portal
url: https://github.com/Connect-Smart/remote-wireguard/
arch:
  - aarch64
  - amd64
  - armv7
apparmor: true
host_network: true
init: false
privileged:
  - NET_ADMIN
  - SYS_MODULE
devices:
  - /dev/net/tun
map:
  - type: config   # toegang tot /data/options.json
    read_only: false
options:
  log_level: info
  portal_url: ""
  enrollment_token: ""
  verify_ssl: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|critical)?
  portal_url: str?
  enrollment_token: str?
  verify_ssl: bool?
  monitor_target: str?
  monitor_interval: int?
